

/*================================================================
 *
 *
 *   文件名称：channel_record.c
 *   创 建 者：肖飞
 *   创建日期：2021年05月23日 星期日 13时40分21秒
 *   修改日期：2022年02月11日 星期五 21时31分02秒
 *   描    述：
 *
 *================================================================*/
#include "channel_record.h"

#include "log.h"

char *get_channel_record_item_stop_reason_des(channel_record_item_stop_reason_t stop_reason)
{
	char *des = "unknow";

	switch(stop_reason) {
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_NONE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_MANUAL);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_AMOUNT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_ENERGY);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DURATION);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_REMOTE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_INSULATION);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_CARD_READER);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_DISPLAY);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_POWER_MODULES);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_DOOR);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_RELAY_ADHESION);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_FORCE_STOP);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_INPUT_OVER_VOLTAGE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_INPUT_LOW_VOLTAGE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ELECTRIC_LEAK_CALIBRATION);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ELECTRIC_LEAK_PROTECT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_PE_PROTECT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BREAKDOWN);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ENERGYMETER);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_CONNECTOR);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_FUNCTION_BOARD_CONNECT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_OVER_TEMPERATURE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ADHESION_P);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ADHESION_N);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_TEMPERATURE_LIMIT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_VOLTAGE_LIMIT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_SOC_ARCHIEVED);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_SOC_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_VOLTAGE_ARCHIEVED);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_VOLTAGE_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_SINGLE_VOLTAGE_ARCHIEVED);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_SINGLE_VOLTAGE_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_INSULATION_FAULT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_INSULATION_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CONNECTOR_OVER_TEMPERATURE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CONNECTOR_TEMPERATURE_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BMS_CONNECTOR_OVER_TEMPERATURE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BMS_CONNECTOR_TEMPERATURE_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CONNECTOR_FAULT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CONNECTOR_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BATTERY_OVER_TEMPERATURE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BATTERY_TEMPERATURE_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_OTHER_FAULT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_OTHER_FAULT_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_OVER_CURRENT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CURRENT_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_ABNORMAL_VOLTAGE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_ABNORMAL_VOLTAGE_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BMS_OTHER_FAULT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BRM_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BCP_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BRO_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BRO_READY_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BCS_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BCL_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BST_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BSD_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_CRO_NOT_READY_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_PRECHARGE_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_INSULATION_EXTERN_VOLTAGE_FAULT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_INSULATION_CHECK_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_INSULATION_FAULT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_DISCHARGE_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_DISCHARGE_FAULT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_ADHESION_CHECK_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_ADHESION_FAULT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_INSULATION_CHECK_WITH_ELECTRIFIED);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_ABNORMAL_VOLTAGE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_CHARGER_NOT_CONNECTED);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_ADHESION_CHECK_L_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_ADHESION_L);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_ADHESION_CHECK_N_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_ADHESION_N);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_CC1_READY_0_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_CC1_READY_1_TIMEOUT);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CHARGER_LOCK_ERROR);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_UNMATCHED_VOLTAGE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BATTERY_VOLTAGE_NOT_CREDIBLE);
			add_des_case(CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BATTERY_CHARGE_DISABLE);

		default: {
		}
		break;
	}

	return des;
}
