

/*================================================================
 *   
 *   
 *   文件名称：channel_record.h
 *   创 建 者：肖飞
 *   创建日期：2021年05月23日 星期日 13时40分28秒
 *   修改日期：2022年02月11日 星期五 21时47分03秒
 *   描    述：
 *
 *================================================================*/
#ifndef _CHANNEL_RECORD_H
#define _CHANNEL_RECORD_H
#ifdef __cplusplus
extern "C"
{
#endif

#ifdef __cplusplus
}
#endif

#include "app_platform.h"
#include "cmsis_os.h"

#include "callback_chain.h"
#include "storage.h"
#include "channels_config.h"

typedef enum {
	//正常结束
	CHANNEL_RECORD_ITEM_STOP_REASON_NONE = 0,
	CHANNEL_RECORD_ITEM_STOP_REASON_MANUAL,
	CHANNEL_RECORD_ITEM_STOP_REASON_AMOUNT,
	CHANNEL_RECORD_ITEM_STOP_REASON_ENERGY,
	CHANNEL_RECORD_ITEM_STOP_REASON_DURATION,
	CHANNEL_RECORD_ITEM_STOP_REASON_REMOTE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS,

	//channels fault
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_INSULATION,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_CARD_READER,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_DISPLAY,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_POWER_MODULES,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_DOOR,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_RELAY_ADHESION,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_FORCE_STOP,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_INPUT_OVER_VOLTAGE,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_INPUT_LOW_VOLTAGE,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ELECTRIC_LEAK_CALIBRATION,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ELECTRIC_LEAK_PROTECT,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_PE_PROTECT,
	CHANNEL_RECORD_ITEM_STOP_REASON_BREAKDOWN,

	//channel fault
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ENERGYMETER,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_CONNECTOR,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_FUNCTION_BOARD_CONNECT,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_OVER_TEMPERATURE,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ADHESION_P,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_ADHESION_N,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_TEMPERATURE_LIMIT,
	CHANNEL_RECORD_ITEM_STOP_REASON_FAULT_VOLTAGE_LIMIT,

	//bms
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_SOC_ARCHIEVED,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_SOC_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_VOLTAGE_ARCHIEVED,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_VOLTAGE_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_SINGLE_VOLTAGE_ARCHIEVED,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_SINGLE_VOLTAGE_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_INSULATION_FAULT,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_INSULATION_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CONNECTOR_OVER_TEMPERATURE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CONNECTOR_TEMPERATURE_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BMS_CONNECTOR_OVER_TEMPERATURE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BMS_CONNECTOR_TEMPERATURE_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CONNECTOR_FAULT,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CONNECTOR_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BATTERY_OVER_TEMPERATURE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BATTERY_TEMPERATURE_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_OTHER_FAULT,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_OTHER_FAULT_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_OVER_CURRENT,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CURRENT_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_ABNORMAL_VOLTAGE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_ABNORMAL_VOLTAGE_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BMS_OTHER_FAULT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BRM_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BCP_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BRO_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BRO_READY_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BCS_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BCL_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BST_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_BSD_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_CRO_NOT_READY_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_PRECHARGE_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_INSULATION_EXTERN_VOLTAGE_FAULT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_INSULATION_CHECK_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_INSULATION_FAULT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_DISCHARGE_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_DISCHARGE_FAULT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_ADHESION_CHECK_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_ADHESION_FAULT,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_INSULATION_CHECK_WITH_ELECTRIFIED,
	CHANNEL_RECORD_ITEM_STOP_REASON_DC_BMS_GB_ABNORMAL_VOLTAGE,
	CHANNEL_RECORD_ITEM_STOP_REASON_CHARGER_NOT_CONNECTED,
	CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_ADHESION_CHECK_L_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_ADHESION_L,
	CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_ADHESION_CHECK_N_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_ADHESION_N,
	CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_CC1_READY_0_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_AC_CHARGER_CC1_READY_1_TIMEOUT,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_CHARGER_LOCK_ERROR,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_UNMATCHED_VOLTAGE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BATTERY_VOLTAGE_NOT_CREDIBLE,
	CHANNEL_RECORD_ITEM_STOP_REASON_BMS_BATTERY_CHARGE_DISABLE,
} channel_record_item_stop_reason_t;

typedef struct {
	uint8_t channel_id;
	uint8_t stop_reason;//channel_record_item_stop_reason_t
} channel_record_item_t;

char *get_channel_record_item_stop_reason_des(channel_record_item_stop_reason_t stop_reason);

#endif //_CHANNEL_RECORD_H
